Draft
industrial-edge/opc-ua-application-getting-started pull request #7
Opened 2024-01-11 08:58 UTC by Bala667

Hi Norman

I am creating the Pull request for this git hub application example, As I made changes, Please review it

Thanks

2024-01-11 09:59 UTC, HummelN7872 requested changes

2024-01-11 09:59 UTC, HummelN7872 commented on docs/Installation.md
> +In your industrial edge devic open the common congigurator and configure the OPC UA connector
spelling mistake "congigurator "

2024-01-11 09:59 UTC, HummelN7872 commented on docs/Installation.md
> +This configuration done localy at the industrial edge Device
locally instead of localy

2024-01-11 09:59 UTC, HummelN7872 commented on README.md
> +When previous steps are configured correctly, data are available in OPC UA Application. Use UA Expert to connect to OPC UA Application at end point `opc.tcp://Ip-Address-of-Edge-Device:4840`. You can
Are you sure about the port 4840? In the documentation it says that the correct port ist 48010

_A client can connect to Edge OPC UA server at end point opc.tcp://Ip-Address-ofEdge-Device:48010._

2024-01-12 08:07 UTC, Bala667 commented
Hi Norman everything is updated you can merge it now, Thanks.

2024-01-12 09:14 UTC, HummelN7872 approved these changes

2024-01-12 09:14 UTC, merged